---
# YAML documents begin with the document separator ---

  # Hosts: where our play will run and options it will run with
- hosts: ubuntu-c

  # Vars: variables that will apply to the play, on all target systems

  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Assemble conf.d to sshd_config
      assemble:
        src: conf.d
        dest: sshd_config

  # Handlers: the list of handlers that are executed as a notify key from a task
...
