---
# YAML documents begin with the document separator ---

# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-

  # Hosts: where our play will run and options it will run with
  hosts: ubuntu-c

  # Vars: variables that will apply to the play, on all target systems

  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Add centos1 to adhoc_group1
      add_host:
        name: centos1
        groups: adhoc_group1, adhoc_group2
  # Handlers: the list of handlers that are executed as a notify key from a task

-
  # Hosts: where our play will run and options it will run with
  hosts: adhoc_group1

  # Vars: variables that will apply to the play, on all target systems

  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Ping all in adhoc_group1
      ping:
  # Handlers: the list of handlers that are executed as a notify key from a task

# Three dots indicate the end of a YAML document
...
