---
# YAML documents begin with the document separator ---

  # Hosts: where our play will run and options it will run with
- hosts: linux

  # Vars: variables that will apply to the play, on all target systems

  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Task 1
      command: /bin/sleep 5
      when: ansible_hostname == "centos1"
      async: 10
      # Here poll 0 means fire and forget
      poll: 0
      register: result1

    - name: Task 2
      command: /bin/sleep 5
      when: ansible_hostname == "centos2"
      async: 10
      poll: 0
      register: result2

    - name: Task 3
      command: /bin/sleep 5
      when: ansible_hostname == "centos3"
      async: 10
      poll: 0
      register: result3

    - name: Task 4
      command: /bin/sleep 30
      when: ansible_hostname == "ubuntu1"
      async: 10
      poll: 0
      register: result4

    - name: Task 5
      command: /bin/sleep 5
      when: ansible_hostname == "ubuntu2"
      async: 10
      poll: 0
      register: result5

    - name: Task 6
      command: /bin/sleep 5
      when: ansible_hostname == "ubuntu3"
      async: 10
      poll: 0
      register: result6

    - name: Show registered context
      debug:
        var: result1

    - name: Show registered context as jinja2
      debug:
        msg: "{{ result1 }}"


  # Handlers: the list of handlers that are executed as a notify key from a task

...
