---
# YAML documents begin with the document separator ---

  # Hosts: where our play will run and options it will run with
- hosts: linux
  gather_facts: False

  # Vars: variables that will apply to the play, on all target systems

  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Task 1
      # sleep random time upto 10 seconds
      command: "/bin/sleep {{ 10 | random }}"

    - name: Task 2
      command: "/bin/sleep {{ 10 | random }}"

    - name: Task 3
      command: "/bin/sleep {{ 10 | random }}"

    - name: Task 4
      command: "/bin/sleep {{ 10 | random }}"

    - name: Task 5
      command: "/bin/sleep {{ 10 | random }}"

    - name: Task 6
      command: "/bin/sleep {{ 10 | random }}"

  # Handlers: the list of handlers that are executed as a notify key from a task

...
