---
control:
  hosts:
    ubuntu-c:
      ansible_connection: local

centos:
  hosts:
    centos1:
      ansible_port: 2222
    centos2:
    centos3:
  vars:
    ansible_user: root
    nginx_root_location: /usr/share/nginx/html

ubuntu:
  hosts:
    ubuntu1:
    ubuntu2:
    ubuntu3:
  vars:
    ansible_become: true
    ansible_become_pass: password
    nginx_root_location: /var/www/html

linux:
  children:
    centos:
    ubuntu:
...