---
-
  # Hosts: where our play will run and options it will run with
  hosts: centos1
  gather_facts: False

  # Vars: variables that will apply to the play, on all target systems
  vars:
    external_example_key: example_value

    external_dict:
      dict_key: This is a dictionary value

    external_inline_dict: {inline_dict_key: This is an inline dictionary value}

    external_named_list:
      - item1
      - item2
      - item3
      - item4

    external_inline_named_list: ["item1", "item2", "item3", "item4"]


  # Tasks: the list of tasks that will be executed within the play, this section
  #         can also be used for pre and post tasks
  tasks:
    - name: Test key value
      debug:
        msg: "{{ external_example_key }}"

    - name: Test named dictionary
      debug:
        msg: "{{ external_dict }}"

    - name: Test named dictionary with dot notation
      debug:
        msg: "{{ external_dict.dict_key }}"

    - name: Test named dictionary with bracket notation
      debug:
        msg: "{{ external_dict['dict_key'] }}"

    - name: Test inline dictionary
      debug:
        msg: "{{ external_inline_dict }}"

    - name: Test inline dictionary with dot notation
      debug:
        msg: "{{ external_inline_dict.inline_dict_key }}"

    - name: Test inline dictionary with bracket notation
      debug:
        msg: "{{ external_inline_dict['inline_dict_key'] }}"

    - name: Test named list
      debug:
        msg: "{{ external_named_list }}"

    - name: Test named list with dot notation
      debug:
        msg: "{{ external_named_list.0 }}"

    - name: Test named list with bracket notation
      debug:
        msg: "{{ external_named_list[0] }}"

    - name: Test inline named list
      debug:
        msg: "{{ external_inline_named_list }}"

    - name: Test inline named list with dot notation
      debug:
        msg: "{{ external_inline_named_list.0 }}"

    - name: Test inline named list with bracket notation
      debug:
        msg: "{{ external_inline_named_list[0] }}"

  # Handlers: the list of handlers that are executed as a notify key from a task

  # Roles: list of roles to be imported into the play
...