---
-
  # Hosts: where our play will run and options it will run with
  hosts: centos1
  gather_facts: False

  # Vars: variables that will apply to the play, on all target systems
  vars:
    dict:
      example_key: example value

  # Tasks: the list of tasks that will be executed within the play, this section
  #         can also be used for pre and post tasks
  tasks:
    - name: Test named dictionary
      debug:
        msg: "{{ dict }}"

    - name: Test named dictionary with dot notation
      debug:
        msg: "{{ dict.example_key }}"

    - name: Test named dictionary with bracket notation
      debug:
        msg: "{{ dict['example_key'] }}"

  # Handlers: the list of handlers that are executed as a notify key from a task

  # Roles: list of roles to be imported into the play
...