---
# YAML documents begin with the document separator ---

  # Hosts: where our play will run and options it will run with
- hosts: linux

  # Vars: variables that will apply to the play, on all target systems

  # Tasks: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Configure a MOTD
      copy:
        content: "Welcome to {{ ansible_distribution }} - Ansible Rocks\n"
        dest: /etc/motd
      notify: MOTD Changed

  # Handlers: the list of handlers that are executed as a notify key from a task
  handlers:
    - name: MOTD Changed
      debug:
        msg: The MOTD was changed
...
