---
-
  # Hosts: where our play will run and options it will run with
  hosts: centos1
  gather_facts: True

  # Vars: variables that will apply to the play, on all target systems

  # Tasks: the list of tasks that will be executed within the play, this section
  #         can also be used for pre and post tasks
  tasks:
    - name: Test hostvars with an ansible fact and collect ansible_port with dot notation
      debug:
        msg: "{{ hostvars[ansible_hostname].ansible_port }}"

    - name: Test hostvars with an ansible fact and collect ansible_port with bracket notation
      debug:
        msg: "{{ hostvars[ansible_hostname]['ansible_port'] }}"

    - name: Test hostvars with an ansible fact and collect ansible_distribution with bracket notation
      debug:
        msg: "{{ hostvars[ansible_hostname]['ansible_distribution'] }}"

  # Handlers: the list of handlers that are executed as a notify key from a task

  # Roles: list of roles to be imported into the play
...